# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "70dc841cdf7d1a135a1d13f63c555d71"
# ⬇ Replace with your production URL before running `shopify app deploy`
application_url = "https://product-configurator-production-3eef.up.railway.app"
embedded = true
name = "Konfig ‑ Product Customizer"

[access_scopes]
scopes = "write_products,read_products,write_orders,read_orders,read_inventory,write_inventory,read_locations,write_publications,read_publications,write_files"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://product-configurator-production-3eef.up.railway.app/auth/callback",
  "https://product-configurator-production-3eef.up.railway.app/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
